CFLAGS = -std=c++17 -O2
LDFLAGS = -lglfw -lvulkan -ldl -lpthread -lX11 -lXxf86vm -lXrandr -lXi

# setup: setup.cpp
# 	g++ $(CFLAGS) -o setup setup.cpp $(LDFLAGS)

presentation: presentation.cpp
	g++ $(CFLAGS) -o presentation presentation.cpp $(LDFLAGS)